**Réseau de neurone Artificiel**

In [ ]:
pip install tensorflow

In [ ]:
#Installation des packages
#on va utiliser une base de donné qui est déja installé sur sklearn
from sklearn import datasets
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
#telecharger la base de données
df=datasets.load_breast_cancer()

In [ ]:
#Découvrir la BD (afficher la description de la bd)
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [ ]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [ ]:
#affichage des données hétérogène
df.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

**Préparer les données (designer les variables dependantes et celle indépendantes)**

In [ ]:
x=df.data #var dependants
y=df.target #var independants

In [ ]:
#standariser les var dependants
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

NB:60% des données sont comprise entre -1 et 1


on doit séparer les données de test et les données d'entrainement

NB:les données de test sont celle qu'on va injecter à notre réseau de neurone pour comprendre le lien entre les variables dépendants et la variable indep,
on les faire passer pour qu'on puisse mettre à jour les poids et proposer un réseau de neurone entrainé et aprés en va utiliser les données de test pour voir la précision de notre réseau de neurone

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.2,random_state=42)

x_train et x_test sont les entrées d'entrainements et les entrées de test /
y_train et y_test sont les sorties d'entrainement et les sorties test /
x_scaled sont les données standarisées qu'on va utiliser pour l'entrainement et le test /
y c'est la variable target /
test_size c'est le size qu'on va donner au parti test =0.2 i-e 20% et 80% au parti entrainement /
random_state pour qu'on puisse trouver la meme chose texte en gras.

In [ ]:
print(x_train.shape,x_test.shape)

(455, 30) (114, 30)


**Construction de réseau de neurone**

NB:
pr construire notre réseau de neurone on doit d'abord spécifier combien de noeud on doit avoir ds la parti entrées,on doit créer les couches cachées,au meme temps spécifier le nbr des noeuds,spécifier quel type de fct d'activation qu'on va utiliser,puis spécifier la sortie.
lui dire aussi comment il doit calculer les poids.


In [ ]:
#Création de réseau de neurone
model=tf.keras.models.Sequential()

**Spécifier la couche d'entrée et la 1er couche caché**

In [ ]:
#units pr spécifier le nbr des noeuds de la couche caché (30 entrées/2=15 (aleatoire))
#pr la parti couche caché on utlise ReLU function
#pr la sorti on veut avoir une sortie entre 0 et 1(des probabilitées) ,donc on utilse Sigmoid function 
#kernel_initializer pour initier les poids
#input_dim pr spécifier la taille de la couche d'entrée (30 car on a 30 varaibles dependantes)
model.add(tf.keras.layers.Dense(units=15,activation='relu',kernel_initializer='uniform',input_dim=30))

**Spécifier la couche de sortie**

In [ ]:
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid',kernel_initializer='uniform'))

In [ ]:
#loss pr définir la fct du cout
#optimizer pr spécifier comment les poids sont mis à jour
#metrics pr calculer la précision de notre modèle
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['binary_accuracy'])

In [ ]:
#voir ce qu'on a construit jusqu'à maintenant
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 15)                465       
                                                                 
 dense_1 (Dense)             (None, 1)                 16        
                                                                 
Total params: 481
Trainable params: 481
Non-trainable params: 0
_________________________________________________________________


NB:on peut visualiser que : 
le modèle est de type sequential/
1er couche caché de 15 noeuds/
couche de sortie d'1 seul noeud.

**Entrainer le réseau de neurone**

In [ ]:
#pr entrainer le réseau de neurone on doit affecter les poids adequadts pr pouvoir faire des prévisions de façon la plus correcte possible
#appliquer le modèle avec fit() sur la bd d'entrainement
#batch_size si no veut passer un nbr précis d'échantillon (élément de la bd) pour mettre à jour les poids (car le fait de faire passer tous les données ça va prendre plus de temps)
#epochs pr préciser le nbr De fois que je vais passer la bd pr entrainer le modèle
model.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
46/46 [==============================] - 1s 1ms/step - loss: 0.6491 - binary_accuracy: 0.8835
Epoch 2/100
46/46 [==============================] - 0s 1ms/step - loss: 0.4634 - binary_accuracy: 0.9231
Epoch 3/100
46/46 [==============================] - 0s 2ms/step - loss: 0.2782 - binary_accuracy: 0.9473
Epoch 4/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1888 - binary_accuracy: 0.9582
Epoch 5/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1464 - binary_accuracy: 0.9648
Epoch 6/100
46/46 [==============================] - 0s 1ms/step - loss: 0.1227 - binary_accuracy: 0.9714
Epoch 7/100
46/46 [==============================] - 0s 2ms/step - loss: 0.1066 - binary_accuracy: 0.9780
Epoch 8/100
46/46 [==============================] - 0s 2ms/step - loss: 0.0958 - binary_accuracy: 0.9780
Epoch 9/100
46/46 [==============================] - 0s 2ms/step - loss: 0.0880 - binary_accuracy: 0.9802
Epoch 10/100
46/46 [==========================

**Tester le modèle**

In [ ]:
#Evaluer le réseau de neurone en utilisant la base de donnée test
test_loss,test_accuracy=model.evaluate(x_test,y_test)
print(f'Test accuracy: {test_accuracy} et Test Loss: {test_loss}')

4/4 [==============================] - 0s 4ms/step - loss: 0.0557 - binary_accuracy: 0.9825
Test accuracy: 0.9824561476707458 et Test Loss: 0.05566602945327759
